language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qt5-default
  - sudo apt-get install libyaml-cpp0.5

script:
  - qmake
  - make