language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qt5-default
  - wget https://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
  - tar -xzf yaml-cpp-0.5.1.tar.gz
  - ls -l
  - cd yaml-cpp-0.5.1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install

script:
  - qmake
  - make