language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qt5-default
  - sudo apt-get install libboost-dev
  - mkdir lib
  - wget https://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
  - tar -xzf yaml-cpp-0.5.1.tar.gz
  - cd yaml-cpp-0.5.1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cp -r ../include/yaml-cpp ../../include/
  - cd ..
  - cd ..

script:
  - qmake
  - make
